#include "nsISupports.idl"

[scriptable, uuid(91180c06-0195-40f0-8940-cccfd06a5e5d)]
interface ilISearchBase : nsISupports
{
  void clearResults();
  void addResult(in AString aValue, 
                 in AString aComment, 
                 in AString aImage, 
                 in AString aStyle);
  void notifyListener(in PRBool aSucceeded);
};
